#########################
# configuration section #
#########################

ZTEXPREFIX=../..

JARTARGET=FlashSend.jar
CLASSTARGETS=FlashSend.class
CLASSEXTRADEPS=
#CLASSEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/java/ztex/*.java)

IHXTARGETS=
IHXEXTRADEPS=
#IHXEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/include/*.h)
EXTRAJARFILES=

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk
